FROM docker.io/debian:trixie
WORKDIR /app
RUN apt-get update && \
	apt-get install -y build-essential mingw-w64 curl

# specific layers
COPY . .
ENV VERSION=0.40
RUN curl http://www.jedrea.com/chmlib/chmlib-${VERSION}.tar.gz --location | tar xzvf - && \
	cd chmlib-${VERSION} && \
	x86_64-w64-mingw32-gcc src/lzx.c -Ofast -flto -static-libgcc -static-libstdc++ -shared -o lzx.dll && \
	install -D lzx.dll -t /app/out
