FROM docker.io/debian:trixie
WORKDIR /app
RUN apt-get update && \
	apt-get install -y build-essential mingw-w64 curl

# specific layers
COPY . .
ENV VERSION=0.14.2
RUN curl https://github.com/g1mv/density/archive/refs/tags/density-${VERSION}.tar.gz --location | tar xzvf - && \
	cd density-density-${VERSION} && \
	patch < ../density.patch && \
	CC=x86_64-w64-mingw32-gcc LD=x86_64-w64-mingw32-ld AR=x86_64-w64-mingw32-ar OS=Windows_NT make -j$(nproc) library && \
	install -D build/libdensity.a build/libdensity.dll -t /app/out
